### ISSUE TITLE
[Bug] Uncaught TypeError: window[this.entrypoint] is not a function

### ISSUE THREAD

**Issue by KaKi87** [pixeldesu/moduleRaid#14]
Hello,

I am getting the following error when calling `new ModuleRaid()` :
```
Uncaught TypeError: window[this.entrypoint] is not a function
    at o.fillModules (moduleraid.ts:201:24)
    at new e (moduleraid.ts:139:10)
```
Thanks

**Comment by KaKi87** [comment]
> What website are you trying to run moduleRaid on?

On [chat2.kaki87.net](https://chat2.kaki87.net/register), which is my own [fosscord](https://github.com/fosscord) instance.
More precisely, I'd like to remove the DoB fieldset, which is [easy](https://git.kaki87.net/KaKi87/fosscord-plugins/src/branch/master/removeRegistrationDateOfBirthFieldset.js), except the form won't submit, which means I also need to access the React component and set a default value (e.g. `1970-01-01`) to unblock it.
> If `webpackJsonp` is not available in `window` you need to specify a custom entrypoint (e.g. https://moduleraid.netlify.app/classes/moduleraid.moduleraid#constructor)

I saw that, which isn't necessary in this case.

Thanks !

**Comment by pixeldesu** [comment]
Hmm, if I run the script on the page via the console it works fine. 

I don't know how you are implementing moduleRaid but maybe you are too early then (moduleRaid tries to call the entrypoint as a function as the last resort, which was some legacy Webpack bundling way)

**Comment by pixeldesu** [comment]
Yeah, I saw the errors prop up a bit more often in other projects too.

I'll see about fixing that injection method, so it doesn't throw errors anymore at least.

**Comment by lucasfq** [comment]
> Yeah, I saw the errors prop up a bit more often in other projects too.
> 
> I'll see about fixing that injection method, so it doesn't throw errors anymore at least.

Hi!
Any news?

**Comment by marcomow** [comment]
I'm getting an error a bit different
> moduleraid.iife.js:1 Uncaught Error: Unknown Webpack structure
    at o.fillModules (moduleraid.iife.js:1:1888)
    at new e (moduleraid.iife.js:1:1001)
    at HTMLScriptElement.<anonymous> (<anonymous>:4:55)

but after activating the debug option, it looks like it is the same issue
> moduleraid.iife.js:1 [moduleRaid] Pushing moduleRaid.arrayArguments[0] into webpackJsonp failed:
TypeError: window[t.entrypoint].push is not a function
TypeError: window[t.entrypoint].push is not a function
    at https://unpkg.com/moduleraid/dist/moduleraid.iife.js:1:1662
    at Array.forEach (<anonymous>)
    at o.fillModules (https://unpkg.com/moduleraid/dist/moduleraid.iife.js:1:1562)
    at new e (https://unpkg.com/moduleraid/dist/moduleraid.iife.js:1:1001)
    at HTMLScriptElement.<anonymous> (<anonymous>:4:55)
  
> moduleraid.iife.js:1 [moduleRaid] Pushing moduleRaid.arrayArguments[1] into webpackJsonp failed:
TypeError: window[t.entrypoint].push is not a function
TypeError: window[t.entrypoint].push is not a function
    at https://unpkg.com/moduleraid/dist/moduleraid.iife.js:1:1662
    at Array.forEach (<anonymous>)
    at o.fillModules (https://unpkg.com/moduleraid/dist/moduleraid.iife.js:1:1562)
    at new e (https://unpkg.com/moduleraid/dist/moduleraid.iife.js:1:1001)
    at HTMLScriptElement.<anonymous> (<anonymous>:4:55)
    
The webpage is https://www.seb.lv/sites/default/files/calc/public/en/kma.html

**Comment by pixeldesu** [comment]
Okay, so an update on this:

First, I have made new releases since:

**6.0.1** fixed an issue with function method injections, these should work again (important for Webpack v3 and earlier).

**6.1.0** introduces a new feature: Entrypoint detection :tada: 

In case of WhatsApp Web, the entrypoint isn't called `webpackJsonp` but `webpackChunkwhatsapp_web_client` and moduleRaid now will try it's best to automatically detect an endpoint if `webpackJsonp` is not the correct one. 

You can now also specify a `strict` option in the constructor, where detection is not run, and if your specified entrypoint (or by default `webpackJsonp`) is not found, you will get an error.

I also fixed the final brute-force injection method so that it doesn't say `window[this.entrypoint] is not a function`, but it will actually return `Unknown Webpack structure` instead.

This hopefully should solve most of the issues from this thread!
